name: document
on:
  workflow_dispatch:
  push:
    branches: [master]
    paths:
      - 'docs/**'

jobs:
  publish-doc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Set up Node.js
        uses: actions/setup-node@master
        with:
          node-version: 16.x

      - name: Install packages and build
        run: |
          pushd ./docs
          yarn
          yarn build
          popd

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GH_TOKEN }}
          publish_dir: ./docs/build
          publish_branch: gh-pages
          cname: react-native-iap.dooboolab.com
