name: Deploy / Documentation

on:
  workflow_dispatch:

  push:
    branches: [main]
    paths:
      - 'docs/**'
      - 'src/**'

jobs:
  publish-documentation:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          cache: 'yarn'

      - name: Install packages and build
        run: |
          yarn || true
          yarn gen:doc || true
          pushd ./docs
          yarn
          yarn build
          popd

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/build
          publish_branch: gh-pages
          cname: react-native-iap.dooboolab.com
